### ISSUE TITLE
Should not require forking / pull request

### ISSUE THREAD

**Issue by dtow55** [learn-co-curriculum/babel-and-react#3]
This 'lab' requires to be forked and a pull request even though there is no work instructed to be done...

**Comment by maxwellbenton** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
