### ISSUE TITLE
links broken on learn.co lesson page

### ISSUE THREAD

**Issue by joshuabamboo** [learn-co-curriculum/babel-and-react#4]
The links on the lesson page (https://learn.co/tracks/full-stack-web-development-v5/react/rendering/babel-and-react?batch_id=306&track_id=31303) are broken. For example, the "Read the wiki" link takes you to
https://learn.co/tracks/full-stack-web-development-v5/react/rendering/%22https://en.wikipedia.org/wiki/Tower_of_Babel%22 instead of https://en.wikipedia.org/wiki/Tower_of_Babel

Note: the github readme does not include the links - this is specific to the learn.co lesson page

@ruthmesfun @Lukeghenco

**Comment by maxwellbenton** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
