### ISSUE TITLE
Links do not work

### ISSUE THREAD

**Issue by Perchitti** [learn-co-curriculum/babel-and-react#6]
All of the links on this page produce a status: 400.

**Comment by maxwellbenton** [comment]
Hi there @Perchitti,

I'm having difficulty reproducing the issue, and all links are currently working, so I'm going to close this for now.

If you can provide further detail about the steps required to reproduce the issue and any additional relevant information about your development environment (local or IDE), I'd be happy to take a second look!

As always, thanks for contributing! 💙
